
export const LOGIN_ROUTE ='/login'
export const REGISTRATION_ROUTE ='/registration'
export const MENU_ROUTE ='/menu'
export const BASE_ROUTE='/'
export const ADMIN_ROUTE='/admin'
export const JOURNALS_ROUTE='/journals'
export const PRODUCT_ROUTE = '/product'
export const CREATE_WORKER_ROUTE='/createWorker'
export const CREATE_WORKER_PLACE_ROUTE='/CreateWorkerPlace'
export const RUCHKA_ROUTE='/ruchka'
export const RUCHKA_MAIN_ROUTE='/ruchkamain'
export const RUCHKA_DEFEC_ROUTE='/ruchka/defec'
export const RUCHKA_REWORK='/ruchka/rework'
export const PLANS_ROUTE='/plans'
export const MATERIAL_ROUTE='/material'